version: '3.8'

services:
  app:
    # Build the app service using the Dockerfile in the app directory
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
  db:
    # Build the database service using the Dockerfile in the db directory
    build:
      context: ./db
      dockerfile: Dockerfile
    # Define a volume for PostgreSQL data
    volumes:
      - ./db:/db

# Define the named volume for PostgreSQL data
volumes:
  db_data:
